- hosts: all
  gather_facts: no
  tasks:
    - name: DEBUG show inventory/user/key mapping
      debug:
        msg:
          - "host={{ inventory_hostname }}"
          - "ansible_user={{ ansible_user | default('unset') }}"
          - "ssh_key_id={{ ssh_key_id | default('unset') }}"
          - "key_files={{ key_files | default('unset') }}"

    - name: DEBUG show ansible_ssh_private_key_file"
      debug:
        var: ansible_ssh_private_key_file

    - name: Stat key file on controller (AWX) - run once
      stat:
        path: "{{ ansible_ssh_private_key_file | default('/nonexistent') }}"
      delegate_to: localhost
      run_once: true
      register: key_stat

    - name: Show stat result (run_once)
      debug:
        var: key_stat
      run_once: true
