---
- name: Install Node Exporter via APT
  hosts: all
  become: yes

  tasks:
    - name: Update APT cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Install Node Exporter package
      ansible.builtin.apt:
        name: prometheus-node-exporter
        state: present

    - name: Ensure Node Exporter service is enabled and running
      ansible.builtin.systemd:
        name: prometheus-node-exporter
        enabled: yes
        state: started
