---
- name: Update and reboot CentOS Stream 10 systems
  hosts: all
  become: true
  gather_facts: true

  tasks:
    - name: Update all packages to latest version
      ansible.builtin.dnf:
        name: "*"
        state: latest
        update_cache: true

    - name: Reboot system (do not wait for it to come back)
      ansible.builtin.shell: |
        (sleep 5 && reboot) &
      async: 0
      poll: 0
      ignore_errors: true
      changed_when: true
      register: reboot_trigger

    - name: Print message
      ansible.builtin.debug:
        msg: "System is rebooting now. Connection will close shortly."