---
- name: Update OpenWrt packages
  hosts: all
  gather_facts: no
  become: no
  vars:
    upgrade_all: true

  tasks:
    - name: Test connectivity
      raw: "echo Connection OK"
      register: connectivity
    - debug:
        msg: "{{ connectivity.stdout }}"

    - name: Update package lists
      raw: "opkg update"
      register: update_result
    - debug:
        msg: "{{ update_result.stdout_lines }}"

    - name: Upgrade all packages
      raw: "opkg list-upgradable | cut -f 1 -d ' ' | xargs -r opkg upgrade"
      when: upgrade_all
      register: upgrade_result
    - debug:
        msg: "{{ upgrade_result.stdout_lines | default('No packages upgraded') }}"

    - name: Reboot router
      raw: "reboot"
      when: upgrade_all
      async: 1
      poll: 0
      ignore_errors: yes

    - name: Wait for router to come back online
      wait_for:
        host: "{{ inventory_hostname }}"
        port: 22
        delay: 30
        timeout: 180
      delegate_to: localhost