---
- name: Update CentOS Stream 10 system packages
  hosts: all
  become: true
  gather_facts: true

  tasks:
    - name: Update all packages to latest version
      ansible.builtin.dnf:
        name: "*"
        state: latest
        update_cache: true
      register: update_result

    - name: Check if reboot is required
      ansible.builtin.command: dnf needs-restarting -r
      register: reboot_check
      failed_when: false
      changed_when: false

    - name: Reboot the system if required
      ansible.builtin.reboot:
        msg: "Reboot initiated by AWX after system update."
        connect_timeout: 10
        reboot_timeout: 900
        pre_reboot_delay: 0
        post_reboot_delay: 30
      when: reboot_check.rc != 0

    - name: Show summary of updated packages
      ansible.builtin.debug:
        msg: >-
          Updated packages:
          {{ update_result.results | map(attribute='name') | list | join(', ') }}