---
- name: Update OpenWrt packages
  hosts: openwrt_routers
  gather_facts: no
  become: yes

  vars:
    upgrade_all: true

  tasks:
    - name: Update package lists
      command: opkg update
      register: update_result

    - debug:
        msg: "{{ update_result.stdout_lines }}"

    - name: Upgrade all packages
      when: upgrade_all
      command: opkg list-upgradable | cut -f 1 -d ' ' | xargs -r opkg upgrade
      register: upgrade_result
      changed_when: "'Upgrading' in upgrade_result.stdout or 'Removing' in upgrade_result.stdout"
      ignore_errors: yes

    - debug:
        msg: "{{ upgrade_result.stdout_lines | default('No packages were upgraded') }}"

    - name: Reboot router (optional)
      when: upgrade_all
      command: reboot
      async: 1
      poll: 0
      ignore_errors: yes

    - name: Wait for router to come back online
      when: upgrade_all
      wait_for:
        host: "{{ inventory_hostname }}"
        port: 22
        delay: 30
        timeout: 180
      delegate_to: localhost
